### ISSUE TITLE
Build guide

### ISSUE THREAD

**Issue by gabrik** [Thagoo/Triton_kernel_xiaomi_msm8917#2]
Any chance to get a build guide?

I mean mostly for the configuration needed by the kernel, somethink like this: https://github.com/android-rpi/device_brcm_rpi3/blob/android10/README#L6 should suffice

Let me explain why this may be usefull, in my case I need to configure the kernel to enable namespacing, in order to be able to run containers on the rolex, hence I need to know how to configure and rebuild the kernel.

**Comment by Thagoo** [comment]
You can generate a new defconfig for your kernel by as you mentioned and it will generate a new file named '.config' .It can be renamed and move it to arch/$ARCH/configs/ to use it next time and you need not to generate defconfig everytime when you build kernel
