### ISSUE TITLE
Tiare status

### ISSUE THREAD

**Issue by ackr-8** [Thagoo/Triton_kernel_xiaomi_msm8917#4]
Just wanted to know if rolex or riva ROMs/Kernels can be easily ported to tiare as everything except the rear camera are the same in these devices, as of now I only have ported GSIs to this device would be really great if a custom ROM works on it as GSIs are really slow.

**Comment by ackr-8** [comment]
Here is the device source : https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/tiare-o-oss
device tree : https://github.com/AndroidBlobs/device_xiaomi_tiare
vendor tree : https://github.com/AndroidBlobs/vendor_xiaomi_tiare

**Comment by Thagoo** [comment]
As you can see in description I have written Tiare as WIP [linux-v4.9] should wait some more time

**Comment by ackr-8** [comment]
Ok thanks for the reply.
